---
title: "Timeseries"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Deep dive on Rides impact using time series predition

#### Loading R packages Data from CO since 11. Nov (data - https://docs.google.com/spreadsheets/d/1USfHwoNz6bLl_wbLbiDJyy5tXnAtTiptRpTnfLdolZ4/edit#gid=957374033)



```{r load_pack, echo=FALSE, include=FALSE}

#### Install and load needed packages
wants <- c("forecast", "MLmetrics", "dplyr", "astsa", "CausalImpact","zoo")
has   <- wants %in% rownames(installed.packages())
if(any(!has)) install.packages(wants[!has])
lapply(wants, library, character.only=T)


```

```{r General Data Overviews, echo=FALSE}
# Load Data 
data=read.csv("/Users/r.nacheva/Downloads/Pronto Data  at Zone - Service - Date level - Data v2.csv") # All

head(data)

```

```{r General Data Overviews1, echo=FALSE, include=FALSE}

data$Date <- as.Date(data$Date,format = "%m/%d/%Y") # Change Data format

data = data[order(data$Date),] # Order by date
data$week_num = strftime(data$Date, format = "%V") # Add weekl number
data$week_day <- weekdays(as.Date(data$Date)) #Add week day

data = as.data.frame(data)
# Chamge back to muneric values
col_factor <- sapply(data, is.factor)
data[col_factor] <- lapply(data[col_factor], as.character)
num_cols <- sapply(data, is.numeric)
data[,num_cols][is.na(data[,num_cols])] <- 0

```


```{r Simple Forecast (without Control period)}
#### Treatment Zones
segment = "period_1_ProntoZones"

#Select yoyr data and aggregate on Date
data_a = subset(data, data$Zone %in% c(710,709,708) & data$Service %in% c(1,33))
data_a$TTS_sum = data_a$TTS* data_a$Rides
data_a$ttrw_sum= data_a$TTRW * data_a$Accepted.Requests
data_a$ETA_sum = data_a$ETA.on.Request.Screen * data_a$Eyeballs

data_a<-summarise_all(group_by_(data_a[c('Date',names(data_a)[sapply(data_a, is.numeric)])],.dots = 'Date'),funs(sum))


# Create you metrics and KPIs
data_a$Utilisation = ifelse(data_a$Supply.Hours==0,0, data_a$Active.Hours/data_a$Supply.Hours)
data_a$ETA_calc = ifelse(data_a$Eyeballs ==0,0, data_a$ETA_sum/(data_a$Eyeballs))
data_a$TTS_calc = ifelse(data_a$Rides ==0,0, data_a$TTS_sum /(data_a$Rides ))
data_a$TTRW_calc = ifelse(data_a$Accepted.Requests ==0,0, data_a$ttrw_sum/(data_a$Accepted.Requests ))

# Create the KPI list
kpis_list = c ('Rides','Revenue', 'Active.Hours', 'Supply.Hours', 'Utilisation', 'Cancelled.by.Driver',
         'Cancelled.by.Passenger','ETA_calc','TTS_calc','TTRW_calc')


p_value = c()
rel_effect = c()
kpi = c()
mean_observed = c()
mean_predicted = c()
segmentation = c()
correl = c()

summary(data_a)

for (i in 1: length(kpis_list)) {

data_all = data_a[c('Date',kpis_list[i])]
dt_all = read.zoo(data_all, format = "%Y-%m-%d")

#Define your pre and post change period. POst period = testing period
pre.period <- as.Date(c("2021-11-01", "2021-12-05"))
post.period <- as.Date(c("2021-12-06", "2022-01-19"))

# Run Causal Impact on all KPIs -daily data with 7 weekdays (nseasons accounts for daily specific trends)
impact_c <- CausalImpact(dt_all, pre.period, post.period, model.args = list(niter = 5000, nseasons = 7))
plot(impact_c)
#summary(impact_c)

p_value_a = impact_c$summary[1,15]
rel_effect_a = impact_c$summary[1,10]
kpi_a = kpis_list[i]

mean_observed_a = impact_c$summary[1,1]
mean_predicted_a = impact_c$summary[1,2]
segmentation_a = segment

p_value = rbind(p_value,p_value_a)
rel_effect = rbind(rel_effect,rel_effect_a)
kpi = rbind(kpi,kpi_a)
mean_observed = rbind(mean_observed,mean_observed_a)
mean_predicted = rbind(mean_predicted,mean_predicted_a)
segmentation = rbind(segmentation,segmentation_a)
correl = rbind(correl,'none')
}

output_1 <- data.frame(segmentation,kpi,mean_observed,mean_predicted,rel_effect,p_value,correl)

#write.table(output_1,"/Users/r.nacheva/Downloads/Pront0_Checks.csv", sep=',', dec='.',row.names=F)


```



```{r Simple Forecast (with Control period correction)}
#### Corrected
segment = "period_1_Corrected"

data_a = subset(data, data$Zone %in% c(710,709,708))# & data$Service %in% c(1,33))    ### Treatment
data_b = subset(data, data$Zone %in% c(711,98))# & data$Service %in% c(1,33)) ### Control

# Create metrics fro both data sets
data_a$ETA_sum = data_a$ETA.on.Request.Screen * data_a$Eyeballs
data_a$TTS_sum = data_a$TTS* data_a$Rides
data_a$ttrw_sum= data_a$TTRW * data_a$Accepted.Requests

data_b$ETA_sum = data_b$ETA.on.Request.Screen * data_b$Eyeballs
data_b$TTS_sum = data_b$TTS* data_b$Rides
data_b$ttrw_sum= data_b$TTRW * data_b$Accepted.Requests

# Aggregate by date
data_a<-summarise_all(group_by_(data_a[c('Date',names(data_a)[sapply(data_a, is.numeric)])],.dots = 'Date'),funs(sum))
data_b<-summarise_all(group_by_(data_b[c('Date',names(data_b)[sapply(data_b, is.numeric)])],.dots = 'Date'),funs(sum))


# Create your KPIs

data_a$Utilisation = ifelse(data_a$Supply.Hours==0,0, data_a$Active.Hours/data_a$Supply.Hours)
data_a$ETA_calc = ifelse(data_a$Eyeballs ==0,0, data_a$ETA_sum/(data_a$Eyeballs ))
data_a$TTS_calc = ifelse(data_a$Rides ==0,0, data_a$TTS_sum /(data_a$Rides ))
data_a$TTRW_calc = ifelse(data_a$Accepted.Requests ==0,0, data_a$ttrw_sum/(data_a$Accepted.Requests ))
data_a$Rev_pRide = ifelse(data_a$Eyeballs ==0,0, data_a$Revenue/(data_a$Rides ))


data_b$Utilisation = ifelse(data_b$Supply.Hours==0,0, data_b$Active.Hours/data_b$Supply.Hours)
data_b$ETA_calc = ifelse(data_b$Eyeballs ==0,0, data_b$ETA_sum/(data_b$Eyeballs ))
data_b$TTS_calc = ifelse(data_b$Rides ==0,0, data_b$TTS_sum /(data_b$Rides ))
data_b$TTRW_calc = ifelse(data_b$Accepted.Requests ==0,0, data_b$ttrw_sum/(data_b$Accepted.Requests ))
data_b$Rev_pRide = ifelse(data_b$Eyeballs ==0,0, data_b$Revenue/(data_b$Rides ))



kpis_list = c ('Rides','Revenue', 'Active.Hours', 'Supply.Hours', 'Utilisation', 'Cancelled.by.Driver',
         'Cancelled.by.Passenger','ETA_calc','TTS_calc','TTRW_calc','Rev_pRide')



p_value = c()
rel_effect = c()
kpi = c()
mean_observed = c()
mean_predicted = c()
segmentation = c()

correl = c()




for (i in 1: length(kpis_list)) {
  
#convert to time series
a = ts(data_a[[kpis_list[i]]])
b = ts(data_b[[kpis_list[i]]])

# correlation check
corrcheck <- cbind(a,b)
correlation <- window(corrcheck,start=1, end=30)
correl_a = cor(correlation)[1,2]
  
data_a_ready = data_a[c('Date',kpis_list[i])]
data_b_ready = data_b[c('Date',kpis_list[i])]

dt_a = read.zoo(data_a_ready, format = "%Y-%m-%d")
dt_b = read.zoo(data_b_ready, format = "%Y-%m-%d")

# Define your pre and post change period
pre.period <- as.Date(c("2021-11-01", "2021-12-05"))
post.period <- as.Date(c("2021-12-06", "2022-01-19"))

impact_c <- CausalImpact(cbind(dt_a,dt_b), pre.period, post.period, model.args = list(niter = 5000, nseasons = 7))
plot(impact_c)
#summary(impact_c)

p_value_a = impact_c$summary[1,15]
rel_effect_a = impact_c$summary[1,10]
kpi_a = kpis_list[i]

mean_observed_a = impact_c$summary[1,1]
mean_predicted_a = impact_c$summary[1,2]
segmentation_a = segment

p_value = rbind(p_value,p_value_a)
rel_effect = rbind(rel_effect,rel_effect_a)
kpi = rbind(kpi,kpi_a)
mean_observed = rbind(mean_observed,mean_observed_a)
mean_predicted = rbind(mean_predicted,mean_predicted_a)
segmentation = rbind(segmentation,segmentation_a)
correl = rbind(correl,correl_a)
}

output_5 <- data.frame(segmentation,kpi,mean_observed,mean_predicted,rel_effect,p_value,correl)


```


```{r Save the output as a csv}
output = rbind(output_1,output_5)
#write.table(output,"/Users/r.nacheva/Downloads/Pronto_220330_all.csv", sep=',', dec='.',row.names=F)

```